# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/mnt/g/Můj disk/0_MAIN/škola/FAV/3.rocnik_23_24/_FAV_ZS_23_24/PC/semestralka/FAV_PC_SP_23_24_BinaryDataInImg"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/mnt/g/Můj disk/0_MAIN/škola/FAV/3.rocnik_23_24/_FAV_ZS_23_24/PC/semestralka/FAV_PC_SP_23_24_BinaryDataInImg"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/g/Můj disk/0_MAIN/škola/FAV/3.rocnik_23_24/_FAV_ZS_23_24/PC/semestralka/FAV_PC_SP_23_24_BinaryDataInImg/CMakeFiles" "/mnt/g/Můj disk/0_MAIN/škola/FAV/3.rocnik_23_24/_FAV_ZS_23_24/PC/semestralka/FAV_PC_SP_23_24_BinaryDataInImg//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/g/Můj disk/0_MAIN/škola/FAV/3.rocnik_23_24/_FAV_ZS_23_24/PC/semestralka/FAV_PC_SP_23_24_BinaryDataInImg/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named FAV_PC_SP_23_24_BinaryDataInImg

# Build rule for target.
FAV_PC_SP_23_24_BinaryDataInImg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FAV_PC_SP_23_24_BinaryDataInImg
.PHONY : FAV_PC_SP_23_24_BinaryDataInImg

# fast build rule for target.
FAV_PC_SP_23_24_BinaryDataInImg/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/build.make CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/build
.PHONY : FAV_PC_SP_23_24_BinaryDataInImg/fast

src/compression.o: src/compression.c.o
.PHONY : src/compression.o

# target to build an object file
src/compression.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/build.make CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/src/compression.c.o
.PHONY : src/compression.c.o

src/compression.i: src/compression.c.i
.PHONY : src/compression.i

# target to preprocess a source file
src/compression.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/build.make CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/src/compression.c.i
.PHONY : src/compression.c.i

src/compression.s: src/compression.c.s
.PHONY : src/compression.s

# target to generate assembly for a file
src/compression.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/build.make CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/src/compression.c.s
.PHONY : src/compression.c.s

src/image.o: src/image.c.o
.PHONY : src/image.o

# target to build an object file
src/image.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/build.make CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/src/image.c.o
.PHONY : src/image.c.o

src/image.i: src/image.c.i
.PHONY : src/image.i

# target to preprocess a source file
src/image.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/build.make CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/src/image.c.i
.PHONY : src/image.c.i

src/image.s: src/image.c.s
.PHONY : src/image.s

# target to generate assembly for a file
src/image.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/build.make CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/src/image.c.s
.PHONY : src/image.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/build.make CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/build.make CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/build.make CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/src/main.c.s
.PHONY : src/main.c.s

src/payload.o: src/payload.c.o
.PHONY : src/payload.o

# target to build an object file
src/payload.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/build.make CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/src/payload.c.o
.PHONY : src/payload.c.o

src/payload.i: src/payload.c.i
.PHONY : src/payload.i

# target to preprocess a source file
src/payload.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/build.make CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/src/payload.c.i
.PHONY : src/payload.c.i

src/payload.s: src/payload.c.s
.PHONY : src/payload.s

# target to generate assembly for a file
src/payload.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/build.make CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/src/payload.c.s
.PHONY : src/payload.c.s

src/utils/binary_data.o: src/utils/binary_data.c.o
.PHONY : src/utils/binary_data.o

# target to build an object file
src/utils/binary_data.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/build.make CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/src/utils/binary_data.c.o
.PHONY : src/utils/binary_data.c.o

src/utils/binary_data.i: src/utils/binary_data.c.i
.PHONY : src/utils/binary_data.i

# target to preprocess a source file
src/utils/binary_data.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/build.make CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/src/utils/binary_data.c.i
.PHONY : src/utils/binary_data.c.i

src/utils/binary_data.s: src/utils/binary_data.c.s
.PHONY : src/utils/binary_data.s

# target to generate assembly for a file
src/utils/binary_data.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/build.make CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/src/utils/binary_data.c.s
.PHONY : src/utils/binary_data.c.s

src/utils/dictionary.o: src/utils/dictionary.c.o
.PHONY : src/utils/dictionary.o

# target to build an object file
src/utils/dictionary.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/build.make CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/src/utils/dictionary.c.o
.PHONY : src/utils/dictionary.c.o

src/utils/dictionary.i: src/utils/dictionary.c.i
.PHONY : src/utils/dictionary.i

# target to preprocess a source file
src/utils/dictionary.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/build.make CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/src/utils/dictionary.c.i
.PHONY : src/utils/dictionary.c.i

src/utils/dictionary.s: src/utils/dictionary.c.s
.PHONY : src/utils/dictionary.s

# target to generate assembly for a file
src/utils/dictionary.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/build.make CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/src/utils/dictionary.c.s
.PHONY : src/utils/dictionary.c.s

src/utils/logger.o: src/utils/logger.c.o
.PHONY : src/utils/logger.o

# target to build an object file
src/utils/logger.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/build.make CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/src/utils/logger.c.o
.PHONY : src/utils/logger.c.o

src/utils/logger.i: src/utils/logger.c.i
.PHONY : src/utils/logger.i

# target to preprocess a source file
src/utils/logger.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/build.make CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/src/utils/logger.c.i
.PHONY : src/utils/logger.c.i

src/utils/logger.s: src/utils/logger.c.s
.PHONY : src/utils/logger.s

# target to generate assembly for a file
src/utils/logger.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/build.make CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/src/utils/logger.c.s
.PHONY : src/utils/logger.c.s

src/utils/memory_management.o: src/utils/memory_management.c.o
.PHONY : src/utils/memory_management.o

# target to build an object file
src/utils/memory_management.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/build.make CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/src/utils/memory_management.c.o
.PHONY : src/utils/memory_management.c.o

src/utils/memory_management.i: src/utils/memory_management.c.i
.PHONY : src/utils/memory_management.i

# target to preprocess a source file
src/utils/memory_management.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/build.make CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/src/utils/memory_management.c.i
.PHONY : src/utils/memory_management.c.i

src/utils/memory_management.s: src/utils/memory_management.c.s
.PHONY : src/utils/memory_management.s

# target to generate assembly for a file
src/utils/memory_management.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/build.make CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/src/utils/memory_management.c.s
.PHONY : src/utils/memory_management.c.s

src/utils/trie.o: src/utils/trie.c.o
.PHONY : src/utils/trie.o

# target to build an object file
src/utils/trie.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/build.make CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/src/utils/trie.c.o
.PHONY : src/utils/trie.c.o

src/utils/trie.i: src/utils/trie.c.i
.PHONY : src/utils/trie.i

# target to preprocess a source file
src/utils/trie.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/build.make CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/src/utils/trie.c.i
.PHONY : src/utils/trie.c.i

src/utils/trie.s: src/utils/trie.c.s
.PHONY : src/utils/trie.s

# target to generate assembly for a file
src/utils/trie.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/build.make CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/src/utils/trie.c.s
.PHONY : src/utils/trie.c.s

src/utils/utils.o: src/utils/utils.c.o
.PHONY : src/utils/utils.o

# target to build an object file
src/utils/utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/build.make CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/src/utils/utils.c.o
.PHONY : src/utils/utils.c.o

src/utils/utils.i: src/utils/utils.c.i
.PHONY : src/utils/utils.i

# target to preprocess a source file
src/utils/utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/build.make CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/src/utils/utils.c.i
.PHONY : src/utils/utils.c.i

src/utils/utils.s: src/utils/utils.c.s
.PHONY : src/utils/utils.s

# target to generate assembly for a file
src/utils/utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/build.make CMakeFiles/FAV_PC_SP_23_24_BinaryDataInImg.dir/src/utils/utils.c.s
.PHONY : src/utils/utils.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... FAV_PC_SP_23_24_BinaryDataInImg"
	@echo "... src/compression.o"
	@echo "... src/compression.i"
	@echo "... src/compression.s"
	@echo "... src/image.o"
	@echo "... src/image.i"
	@echo "... src/image.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/payload.o"
	@echo "... src/payload.i"
	@echo "... src/payload.s"
	@echo "... src/utils/binary_data.o"
	@echo "... src/utils/binary_data.i"
	@echo "... src/utils/binary_data.s"
	@echo "... src/utils/dictionary.o"
	@echo "... src/utils/dictionary.i"
	@echo "... src/utils/dictionary.s"
	@echo "... src/utils/logger.o"
	@echo "... src/utils/logger.i"
	@echo "... src/utils/logger.s"
	@echo "... src/utils/memory_management.o"
	@echo "... src/utils/memory_management.i"
	@echo "... src/utils/memory_management.s"
	@echo "... src/utils/trie.o"
	@echo "... src/utils/trie.i"
	@echo "... src/utils/trie.s"
	@echo "... src/utils/utils.o"
	@echo "... src/utils/utils.i"
	@echo "... src/utils/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

