//
// Author: Lenovo
// Date: 07.11.2023
// Description: 
//

#ifndef FAV_PC_SP_23_24_BINARYDATAINIMG_COMPRESS_H
#define FAV_PC_SP_23_24_BINARYDATAINIMG_COMPRESS_H

#endif //FAV_PC_SP_23_24_BINARYDATAINIMG_COMPRESS_H
